### ISSUE TITLE
Unit tests missed ! Help wanted !

### ISSUE THREAD

**Issue by iusehooks** [iusehooks/useInputDebounce#1]
Looking for someone who wants to contribute writing unit tests using react-testing-library!

**Comment by jyothisankarreddy** [comment]
Hi I can give a try. I have written Unittest in Python, hoping that will be same for react as well.

**Comment by iusehooks** [comment]
Not exactly 😀

**Comment by jyothisankarreddy** [comment]
Ok no problem, You tell me I will learn and do it.
